//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public string dniAlumno { get; set; }
        public string nombreAlumno { get; set; }
        public string apellidoAlumno { get; set; }
        public int edadAlumno { get; set; }
        public string sexoAlumno { get; set; }
        public string direccionAlumno { get; set; }
        public string nombreApoderadoAlumno { get; set; }
        public string numeroTelefonoApoderado { get; set; }
    }
}
