//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Colegio_DBEntities : DbContext
    {
        public Colegio_DBEntities()
            : base("name=Colegio_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<alumno> alumno { get; set; }
    
        public virtual int agregaralumno(string dniAlumno, string nombreAlumno, string apellidoAlumno, Nullable<int> edadAlumno, string sexoAlumno, string direccionAlumno, string nombreApoderadoAlumno, string numeroTelefonoApoderado)
        {
            var dniAlumnoParameter = dniAlumno != null ?
                new ObjectParameter("dniAlumno", dniAlumno) :
                new ObjectParameter("dniAlumno", typeof(string));
    
            var nombreAlumnoParameter = nombreAlumno != null ?
                new ObjectParameter("nombreAlumno", nombreAlumno) :
                new ObjectParameter("nombreAlumno", typeof(string));
    
            var apellidoAlumnoParameter = apellidoAlumno != null ?
                new ObjectParameter("apellidoAlumno", apellidoAlumno) :
                new ObjectParameter("apellidoAlumno", typeof(string));
    
            var edadAlumnoParameter = edadAlumno.HasValue ?
                new ObjectParameter("edadAlumno", edadAlumno) :
                new ObjectParameter("edadAlumno", typeof(int));
    
            var sexoAlumnoParameter = sexoAlumno != null ?
                new ObjectParameter("sexoAlumno", sexoAlumno) :
                new ObjectParameter("sexoAlumno", typeof(string));
    
            var direccionAlumnoParameter = direccionAlumno != null ?
                new ObjectParameter("direccionAlumno", direccionAlumno) :
                new ObjectParameter("direccionAlumno", typeof(string));
    
            var nombreApoderadoAlumnoParameter = nombreApoderadoAlumno != null ?
                new ObjectParameter("nombreApoderadoAlumno", nombreApoderadoAlumno) :
                new ObjectParameter("nombreApoderadoAlumno", typeof(string));
    
            var numeroTelefonoApoderadoParameter = numeroTelefonoApoderado != null ?
                new ObjectParameter("numeroTelefonoApoderado", numeroTelefonoApoderado) :
                new ObjectParameter("numeroTelefonoApoderado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("agregaralumno", dniAlumnoParameter, nombreAlumnoParameter, apellidoAlumnoParameter, edadAlumnoParameter, sexoAlumnoParameter, direccionAlumnoParameter, nombreApoderadoAlumnoParameter, numeroTelefonoApoderadoParameter);
        }
    }
}
